//
// Created by Mikołaj Olesiński on 13/12/2023.
//

#ifndef TEP_LAB04DZIECICZENIE_CNODELEAFVARIABLE_H
#define TEP_LAB04DZIECICZENIE_CNODELEAFVARIABLE_H


class cNodeLeafVariable {

};


#endif //TEP_LAB04DZIECICZENIE_CNODELEAFVARIABLE_H
