//
// Created by Mikołaj Olesiński on 13/12/2023.
//

#ifndef TEP_LAB04DZIECICZENIE_CNODETRIGOPERATOR_H
#define TEP_LAB04DZIECICZENIE_CNODETRIGOPERATOR_H


class cNodeTrigOperator {

};


#endif //TEP_LAB04DZIECICZENIE_CNODETRIGOPERATOR_H
